name: Cucumber Integration Tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

concurrency:
  group: ${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run hostname
      run: hostname

    - name: Fix host entry
      run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts

    - name: Show hosts
      run: cat /etc/hosts

    - name: Checkout master
      uses: actions/checkout@v6

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Fix Docker socket permissions
      run: sudo chmod 666 /var/run/docker.sock

    - name: Build node-app-server image
      working-directory: all-in-one-apim/modules/integration-v2/tests-common/testcontainers/src/main/resources/nodeapps
      run: |
        docker build -t node-app-server:local .
        docker images node-app-server:local
        docker run --rm node-app-server:local echo "Image works!"
        sleep 5

    - name: Configure testcontainers
      run: |
        echo "pull.policy=org.testcontainers.images.DefaultPullPolicy" > ~/.testcontainers.properties

    - name: Tag image as node-app-server:latest for tests
      run: |
        docker tag node-app-server:local node-app-server:latest

    - name: Build product-apim with Test.
      run: mvn clean install --file all-in-one-apim/pom.xml -DskipBenchMarkTest=true -Dmaven.test.skip=true

    - name: Replace keystore files
      run: |
        SRC_TRUSTSTORE="all-in-one-apim/modules/integration-v2/client-truststore.jks"
        SRC_CARBON="all-in-one-apim/modules/integration-v2/wso2carbon.jks"
        TARGET_DIR="all-in-one-apim/modules/p2-profile/product/target/wso2carbon-core-4.11.18/repository/resources/security"
        cp "$SRC_TRUSTSTORE" "$TARGET_DIR/client-truststore.jks"
        cp "$SRC_CARBON" "$TARGET_DIR/wso2carbon.jks"
        echo "Keystore files replaced successfully"

    - name: Run Cucumber Tests
      run: |
        cd all-in-one-apim/modules/integration-v2/
        mvn clean install -Ddocker.extra.hosts="--add-host=host.docker.internal:host-gateway"
